// MIT License
//
// Copyright (c) 2026 Libre Ephemeris Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/// Full accuracy validation: compare le_calc vs swetest.
///
/// Reads the accuracy report CSV generated by tools/validate_accuracy.py,
/// runs le_calc for each (jd, planet) pair, and asserts tolerances.
///
/// Run: cargo test --test validate_accuracy -- --nocapture

use std::collections::HashMap;
use std::path::PathBuf;
use libre_ephemeris::calc::le_calc_ut;
use libre_ephemeris::constants;

fn data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests")
}

fn load_csv(filename: &str) -> Vec<Vec<String>> {
    let path = data_dir().join(filename);
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("Cannot open {}", path.display()));
    let mut rows = Vec::new();
    for line in content.lines() {
        if line.trim().is_empty() || line.starts_with("jd") { continue; }
        let row: Vec<String> = line.split(',').map(|s| s.trim().to_string()).collect();
        if !row.is_empty() { rows.push(row); }
    }
    rows
}

fn angular_separation(x1: f64, y1: f64, z1: f64, x2: f64, y2: f64, z2: f64) -> f64 {
    let d1 = (x1 * x1 + y1 * y1 + z1 * z1).sqrt();
    let d2 = (x2 * x2 + y2 * y2 + z2 * z2).sqrt();
    if d1 < 1e-15 || d2 < 1e-15 { return 0.0; }
    let dot = (x1 * x2 + y1 * y2 + z1 * z2) / (d1 * d2);
    dot.clamp(-1.0, 1.0).acos()
}

fn rad_to_arcsec(rad: f64) -> f64 {
    rad * 206264.80624709636
}

const ANALYTICAL_JD_MIN: f64 = 2451545.0 - 50.0 * 365.25;
const ANALYTICAL_JD_MAX: f64 = 2451545.0 + 50.0 * 365.25;

const TOLERANCE_AS: f64 = 3000.0;

#[test]
fn test_validate_accuracy() {
    let rows = load_csv("accuracy_report.csv");
    if rows.is_empty() {
        eprintln!("Skipping: no accuracy report. Run tools/validate_accuracy.py --binary first.");
        return;
    }

    let flags = constants::LE_FLG_XYZ | constants::LE_FLG_J2000
        | constants::LE_FLG_NOABERR | constants::LE_FLG_NOGDEFL | constants::LE_FLG_NOBIRR | constants::LE_FLG_NONUT;

    let mut max_sep: HashMap<i32, f64> = HashMap::new();
    let mut total = 0u32;
    let mut skipped = 0u32;
    let mut errors = 0u32;
    let mut failures = 0u32;

    for row in &rows {
        if row.len() < 8 { continue; }
        let jd_ut: f64 = match row[0].parse() {
            Ok(v) => v,
            Err(_) => { skipped += 1; continue; }
        };
        if jd_ut < ANALYTICAL_JD_MIN || jd_ut > ANALYTICAL_JD_MAX { skipped += 1; continue; }
        let planet: i32 = match row[1].parse() {
            Ok(v) => v,
            Err(_) => { skipped += 1; continue; }
        };
        if planet == 0 || planet == 1 || planet == 9 || planet == 10 || planet == 17 { skipped += 1; continue; }

        let x_swetest: f64 = match row[5].parse() { Ok(v) => v, Err(_) => { skipped += 1; continue; } };
        let y_swetest: f64 = match row[6].parse() { Ok(v) => v, Err(_) => { skipped += 1; continue; } };
        let z_swetest: f64 = match row[7].parse() { Ok(v) => v, Err(_) => { skipped += 1; continue; } };

        let mut xx = [0.0_f64; 24];
        let mut serr = [0_i8; 256];
        let rc = unsafe {
            le_calc_ut(jd_ut, planet, flags, xx.as_mut_ptr(), serr.as_mut_ptr())
        };
        if rc != 0 || xx[0].is_nan() || xx[1].is_nan() || xx[2].is_nan() {
            errors += 1;
            continue;
        }

        let sep = angular_separation(x_swetest, y_swetest, z_swetest, xx[0], xx[1], xx[2]);
        let sep_as = rad_to_arcsec(sep);
        if sep_as > TOLERANCE_AS {
            failures += 1;
        }
        let entry = max_sep.entry(planet).or_insert(0.0);
        if sep_as > *entry { *entry = sep_as; }
        total += 1;
    }

    println!("Validation results (le_calc vs swetest):");
    println!("  Total test cases: {}", rows.len());
    println!("  Processed: {}", total);
    println!("  Skipped: {}", skipped);
    println!("  Errors: {}", errors);
    println!("  Failures (>{} arcsec): {}", TOLERANCE_AS, failures);

    let mut planets: Vec<_> = max_sep.keys().collect();
    planets.sort();
    for p in planets {
        println!("  Planet {}: max={:.1}\"", p, max_sep[p]);
    }

    assert!(errors == 0, "{} errors during validation", errors);
    assert!(failures == 0, "{} positions exceed {} arcsec tolerance", failures, TOLERANCE_AS);
}
